# Generated by Django 2.1.1 on 2018-09-18 05:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('fix_weapon', models.CharField(default='', max_length=128)),
                ('fix_left', models.CharField(default='', max_length=128)),
                ('fix_right', models.CharField(default='', max_length=128)),
                ('PLD_CURRENT', models.BigIntegerField(default=0)),
                ('WAR_CURRENT', models.BigIntegerField(default=0)),
                ('DRK_CURRENT', models.BigIntegerField(default=0)),
                ('WHM_CURRENT', models.BigIntegerField(default=0)),
                ('SCH_CURRENT', models.BigIntegerField(default=0)),
                ('AST_CURRENT', models.BigIntegerField(default=0)),
                ('BRD_CURRENT', models.BigIntegerField(default=0)),
                ('MCH_CURRENT', models.BigIntegerField(default=0)),
                ('MNK_CURRENT', models.BigIntegerField(default=0)),
                ('NIN_CURRENT', models.BigIntegerField(default=0)),
                ('DRG_CURRENT', models.BigIntegerField(default=0)),
                ('SAM_CURRENT', models.BigIntegerField(default=0)),
                ('BLM_CURRENT', models.BigIntegerField(default=0)),
                ('SMN_CURRENT', models.BigIntegerField(default=0)),
                ('RDM_CURRENT', models.BigIntegerField(default=0)),
                ('PLD_BIS', models.BigIntegerField(default=0)),
                ('WAR_BIS', models.BigIntegerField(default=0)),
                ('DRK_BIS', models.BigIntegerField(default=0)),
                ('WHM_BIS', models.BigIntegerField(default=0)),
                ('SCH_BIS', models.BigIntegerField(default=0)),
                ('AST_BIS', models.BigIntegerField(default=0)),
                ('BRD_BIS', models.BigIntegerField(default=0)),
                ('MCH_BIS', models.BigIntegerField(default=0)),
                ('MNK_BIS', models.BigIntegerField(default=0)),
                ('NIN_BIS', models.BigIntegerField(default=0)),
                ('DRG_BIS', models.BigIntegerField(default=0)),
                ('SAM_BIS', models.BigIntegerField(default=0)),
                ('BLM_BIS', models.BigIntegerField(default=0)),
                ('SMN_BIS', models.BigIntegerField(default=0)),
                ('RDM_BIS', models.BigIntegerField(default=0)),
            ],
        ),
    ]
